#NAME THE PIPELINE SAME AS FILE (WITHOUT ".yml")

# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# trigger:
# - main

resources:
  repositories:
    - repository: self
      trigger: none

variables:
  tag: '$(Build.BuildId)'
  resource-group: 'testRG'
  location: 'eastus'
  templateFile: '.azure/bicep/acr.bicep'
  azureserviceconnection: 'azureconn'
  subscriptionId: 'dbdcf2e9-3d4a-48c4-b9f5-cc4e9a3d6123'

stages:
- stage: Build
  displayName: Create ACR for images
  jobs:
  - job: Build
    pool:
      name: Default
      vmImage: ubuntu-latest
    steps:
    #Create ACR to keep docker images
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy ACR Bicep
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'azureconn'
        subscriptionId: '$(subscriptionId)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'testRG'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: '$(templateFile)'
        deploymentMode: 'Incremental'
        deploymentOutputs: 'acr-json'
    
    #Parse ACR login server variable
    - task: PowerShell@2
      displayName: Parse Bicep Output
      inputs:
        targetType: 'inline'
        script: |
          $var=ConvertFrom-Json '$(acr-json)'
          $value=$var.acrloginServer.value
          Write-Host "##vso[task.setvariable variable=acrloginserver;]$value"
          echo $acrloginserver
    # docker compose build images
    - task: DockerCompose@0
      displayName: Build Docker Compose
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'azureconn'
        azureContainerRegistry: '$(acrloginserver)'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Build services'
        additionalImageTags: '$(Build.BuildNumber)'
        includeLatestTag: true
    - task: DockerCompose@0
      displayName: Push Docker Compose
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: $(azureserviceconnection)
        azureContainerRegistry: '$(acrloginserver)'
        dockerComposeFile: '**/docker-compose.yml'
        projectName: 
        action: 'Push services'
        additionalImageTags: '$(Build.BuildNumber)'
        includeLatestTag: true
